const level1 = new Level(
     [
        new Coin(1),
        new Coin(1),
        new Coin(1),
        new Coin(1),
        new Coin(1),
        new Coin(1),
        new Coin(0),
        new Coin(0),
        new Coin(0),
        new Coin(0),
        new Coin(0),
        new Coin(0),
        new Coin(0),
        new Coin(0),
        new Coin(0),
    ],
    [
        new Bottle(0),
        new Bottle(1),
        new Bottle(0),
        new Bottle(1),
        new Bottle(0),
        new Bottle(1),
        new Bottle(0),
        new Bottle(1),
        new Bottle(0),
        new Bottle(1),
        new Bottle(0),
        new Bottle(1),
        new Bottle(0),
        new Bottle(1),
        new Bottle(0),
    ],
    [   
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new LittleChicken(),
        new LittleChicken(),
        new LittleChicken(),
        new Endboss(),
    ],
    [
        new Cloud(),
        new Cloud(),
        new Cloud(),
        new Cloud(),
    ],
    [
        new BackgroundObject('img/5_background/layers/air.png', -827),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', -827),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', -827),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', -827),
        new BackgroundObject('img/5_background/layers/air.png', 0),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/air.png', 827),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 827),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 827),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 827),
        new BackgroundObject('img/5_background/layers/air.png', 827 * 2),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 827 * 2),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 827 * 2),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 827 * 2),
        new BackgroundObject('img/5_background/layers/air.png', 827 * 3),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 827 * 3),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 827 * 3),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 827 * 3),
        new BackgroundObject('img/5_background/layers/air.png', 827 * 4),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 827 * 4),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 827 * 4),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 827 * 4),
        new BackgroundObject('img/5_background/layers/air.png', 827 * 5),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 827 * 5),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 827 * 5),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 827 * 5),
        new BackgroundObject('img/5_background/layers/air.png', 827 * 6),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 827 * 6),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 827 * 6),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 827 * 6),
    ],
   
);      




// let level1;

// function initLevel() {
//     level1 = new Level(
//         [
//             new Chicken(),
//             new Chicken(),
//             new Chicken(),
//             new Chicken(),
//             new Chicken(),
//             new Chicken(),
//             new Chicken(),
//             new Chicken(),
//             new Chicken(),
//             new Chicken(),
//             new Chicken(),
//             new Endboss(),
//         ],
//         [
//             new Cloud(),
//             new Cloud(),
//             new Cloud(),
//             new Cloud(),
//         ],
//         [
//             new BackgroundObject('img/5_background/layers/air.png', -827),
//             new BackgroundObject('img/5_background/layers/3_third_layer/2.png', -827),
//             new BackgroundObject('img/5_background/layers/2_second_layer/2.png', -827),
//             new BackgroundObject('img/5_background/layers/1_first_layer/2.png', -827),
//             new BackgroundObject('img/5_background/layers/air.png', 0),
//             new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 0),
//             new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 0),
//             new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 0),
//             new BackgroundObject('img/5_background/layers/air.png', 827),
//             new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 827),
//             new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 827),
//             new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 827),
//             new BackgroundObject('img/5_background/layers/air.png', 827 * 2),
//             new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 827 * 2),
//             new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 827 * 2),
//             new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 827 * 2),
//             new BackgroundObject('img/5_background/layers/air.png', 827 * 3),
//             new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 827 * 3),
//             new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 827 * 3),
//             new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 827 * 3),
//             new BackgroundObject('img/5_background/layers/air.png', 827 * 4),
//             new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 827 * 4),
//             new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 827 * 4),
//             new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 827 * 4),
//             new BackgroundObject('img/5_background/layers/air.png', 827 * 5),
//             new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 827 * 5),
//             new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 827 * 5),
//             new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 827 * 5),
//             new BackgroundObject('img/5_background/layers/air.png', 827 * 6),
//             new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 827 * 6),
//             new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 827 * 6),
//             new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 827 * 6),
//         ],
    
//     );
// }
